name: release

on:
  push:
    branches:
      - master
      - mainnet/main
    tags:
      - v*

env:
  # bleh
  MAINNET: ${{ github.ref == 'refs/heads/mainnet/main' || (startsWith(github.ref,'refs/tags/v') && ( contains(github.ref,'.0.') || contains(github.ref,'.2.') || contains(github.ref,'.4.') || contains(github.ref,'.6.') || contains(github.ref,'.8.') )) }}
  GOLANG_CROSS_VERSION: v1.15.2
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v2
      - name: release dry-run
        run: make release-dry-run
      - if: startsWith(github.ref,'refs/tags/v') && github.repository == 'ovrclk/akash'
        name: setup release environment
        run: |-
          echo 'DOCKER_USERNAME=${{secrets.DOCKERHUB_USERNAME}}' > .release-env
          echo 'DOCKER_PASSWORD=${{secrets.DOCKERHUB_PASSWORD}}' >> .release-env
          echo 'GITHUB_TOKEN=${{secrets.GORELEASER_ACCESS_TOKEN}}' >> .release-env
      - if: startsWith(github.ref,'refs/tags/v') && github.repository == 'ovrclk/akash'
        name: release publish
        run: make release
